### ISSUE TITLE
Exit Code is 0 if XML file is invalid

### ISSUE THREAD

**Issue by JulianBirch** [inex-solutions/configgen#7]
You get a large exception trace, but exit code of 0.

**Comment by roblevine** [comment]
Hi Julian,

Which version of ConfigGen are you running, and in exactly what way is the file invalid?
I've tried with a file that was not well formed and get a non-zero exit code. Do you literally mean invalid in the technical sense (as in not valid against a schema)?

Thanks,

**Comment by JulianBirch** [comment]
Hi Rob:

2.0.24-beta (latest on NuGet). Mismatched start and end tag.
Just verified using %ERRORLEVEL%. Still 0.

Thanks,

**Comment by roblevine** [comment]
This is very strange indeed. I can't recreate the issue.
Can you share the xml?

When I try the same, I get a non-zero error code:

> C:\Dev\git\configgen\src\ConfigGen.ConsoleApp\bin\Debug>cfg
> 
> ConfigGen v2.0.24.0 - Configuration file generation tool
> (c)2010-2017 - Rob Levine and other contributors - https://github.com/inex-solutions/configgen
> \--
> 
> Generation process failed:
> System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not closed: xmlRoot. Line 1, position 102.
>    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
>    at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
>    at System.Xml.XmlTextReaderImpl.ThrowUnclosedElements()
>    at System.Xml.XmlTextReaderImpl.ParseElementContent()
>    at System.Xml.XmlTextReaderImpl.Read()
>    at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
>    at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
>    at System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
>    at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
>    at System.Xml.Linq.XElement.Load(Stream stream, LoadOptions options)
>    at ConfigGen.Templating.Xml.TemplateLoader.LoadTemplate(Stream templateStream) in C:\Dev\git\configgen\src\ConfigGen.Templating.Xml\TemplateLoader.cs:line 39 ('TemplateLoadError' in 'XmlTemplate')
> 
> C:\Dev\git\configgen\src\ConfigGen.ConsoleApp\bin\Debug>echo %ERRORLEVEL%
> 3
> 
> C:\Dev\git\configgen\src\ConfigGen.ConsoleApp\bin\Debug>

The xml I am using is this:

```
<?xml version="1.0" encoding="utf-8"?>
<xmlRoot>
	<Value1>[%Value1%]</Value1>
	<Value2>[%Value2%]</Value2>
	
```

(note the missing closing element)
